"""manysql logical-plan IR.

The IR is relational algebra over batch, single-source, read-only data.
See SCOPE.md for what is and is not representable.
"""

from manysql.ir.expr import (
    AggCall,
    AggKind,
    Between,
    BinaryOp,
    Case,
    Cast,
    ColumnRef,
    ExistsSubquery,
    Expr,
    FrameBound,
    FrameBoundKind,
    FrameMode,
    FuncCall,
    InList,
    InSubquery,
    IsNull,
    Literal,
    NullsOrder,
    Op,
    OrderKey,
    ScalarSubquery,
    SortDirection,
    UnaryOp,
    WindowCall,
    WindowFrame,
    WindowKind,
)
from manysql.ir.plan import (
    Aggregate,
    Apply,
    ApplyKind,
    CTEBinding,
    ColumnSchema,
    Distinct,
    Filter,
    Join,
    JoinKind,
    Limit,
    Plan,
    Project,
    RecursiveCTE,
    Scan,
    SetOp,
    SetOpKind,
    Sort,
    Window,
    WithCTE,
)
from manysql.ir.printer import render_expr, render_plan
from manysql.ir.types import (
    BOOL,
    DATE_T,
    FLOAT,
    INT,
    NULL,
    TEXT,
    TIMESTAMP,
    IRType,
    PyValue,
    TypeKind,
)

__all__ = [
    # types
    "IRType",
    "TypeKind",
    "PyValue",
    "INT",
    "FLOAT",
    "TEXT",
    "BOOL",
    "DATE_T",
    "TIMESTAMP",
    "NULL",
    # expressions
    "Expr",
    "Literal",
    "ColumnRef",
    "BinaryOp",
    "UnaryOp",
    "FuncCall",
    "Case",
    "Cast",
    "InList",
    "IsNull",
    "Between",
    "AggCall",
    "AggKind",
    "WindowCall",
    "WindowKind",
    "WindowFrame",
    "FrameMode",
    "FrameBound",
    "FrameBoundKind",
    "ScalarSubquery",
    "ExistsSubquery",
    "InSubquery",
    "Op",
    "OrderKey",
    "SortDirection",
    "NullsOrder",
    # plan nodes
    "Plan",
    "ColumnSchema",
    "Scan",
    "Project",
    "Filter",
    "Join",
    "JoinKind",
    "Aggregate",
    "Window",
    "Sort",
    "Limit",
    "Distinct",
    "SetOp",
    "SetOpKind",
    "WithCTE",
    "CTEBinding",
    "RecursiveCTE",
    "Apply",
    "ApplyKind",
    # printer
    "render_plan",
    "render_expr",
]
