"""Schemas for SemanticConfig (executor knobs) and DialectSpec (codegen input)."""

from manysql.spec.dialect import (
    CaseSyntax,
    CastSyntax,
    CommentStyle,
    DialectSpec,
    DivergenceLevel,
    IdentifierQuote,
    JoinSyntax,
    LimitSyntax,
    NullLiteral,
    OrderByPosition,
    SemanticDivergences,
    StringQuote,
    SurfaceSpec,
    WildcardChar,
)
from manysql.spec.semantics import (
    BoolTruthiness,
    CaseFold,
    CoercionRule,
    CountDistinctNull,
    DivByZero,
    IntDivision,
    NullOrder,
    SemanticConfig,
    SetOpDefault,
    StringConcatOp,
    WindowFrameDefault,
)

__all__ = [
    "SemanticConfig",
    "CaseFold",
    "NullOrder",
    "DivByZero",
    "IntDivision",
    "SetOpDefault",
    "BoolTruthiness",
    "CountDistinctNull",
    "WindowFrameDefault",
    "StringConcatOp",
    "CoercionRule",
    "DialectSpec",
    "DivergenceLevel",
    "SurfaceSpec",
    "SemanticDivergences",
    "CommentStyle",
    "StringQuote",
    "IdentifierQuote",
    "JoinSyntax",
    "OrderByPosition",
    "LimitSyntax",
    "CastSyntax",
    "CaseSyntax",
    "NullLiteral",
    "WildcardChar",
]
